name: Simple Build (No Dependencies)

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'macos'
        type: choice
        options:
          - macos
          - windows

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_BUILD_JOBS: 1
  RUST_BACKTRACE: 1

jobs:
  build-simple:
    runs-on: ${{ github.event.inputs.platform == 'macos' && 'macos-latest' || 'windows-latest' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install minimal Rust dependencies
        run: |
          if [ "${{ github.event.inputs.platform }}" = "macos" ]; then
            rustup target add x86_64-apple-darwin aarch64-apple-darwin
          else
            rustup target add x86_64-pc-windows-msvc
          fi
          cargo install tauri-cli --version "1.0.4"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app (minimal)
        run: |
          if [ "${{ github.event.inputs.platform }}" = "macos" ]; then
            # Solo construir para la arquitectura nativa
            if [ "$(uname -m)" = "arm64" ]; then
              cargo tauri build --target aarch64-apple-darwin --release
            else
              cargo tauri build --target x86_64-apple-darwin --release
            fi
          else
            cargo tauri build --target x86_64-pc-windows-msvc --release
          fi
        env:
          CARGO_TARGET_DIR: src-tauri/target-simple
          CARGO_BUILD_JOBS: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.platform }}-simple
          path: |
            src-tauri/target-simple/*/release/bundle/
          retention-days: 30
